### PR TITLE
Do not divide by zero when the cell in infinite

### LINKED ISSUE #89: Crashing examples
In addition to what I mentioned in #88, the `minimization` example panics:
```
thread 'main' panicked at 'Potential energy is infinite!', /home/antoinewdg/Development/lumol/src/core/src/sys/compute.rs:119
```

I also get warnings on `mc_npt_spce` and `mc_npt_ethane`, is this intentional ?
```
Warning: No potential defined for the pair (H, O) (from /home/antoinewdg/Development/lumol/src/core/src/sys/interactions.rs:181)
Warning: No potential defined for the pair (H, H) (from /home/antoinewdg/Development/lumol/src/core/src/sys/interactions.rs:181)
Initial energy: -76663.13161568451
```
```
Warning: Tried to increase the maximum amplitude for translations to more than the set maximum. (from /home/antoinewdg/Development/lumol/src/core/src/sim/mc/moves/translate.rs:140)
Warning: Tried to increase the maximum amplitude for rotations to more than 180°. (from /home/antoinewdg/Development/lumol/src/core/src/sim/mc/moves/rotate.rs:125)
```

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #89.

The first commit changes should not be controversial, as we assert that there are not reciprocal vectors and that tail correction does not make sense in infinite cells.

The second one is more open to discussion. When computing pressure/stress/virial, I set the volume to 1 and carry on with the computation.

TODO: 
- [x] Decide what to do for pressure/virial/stress
- [x] Add tests for pressure/virial/stress with infinite cells

### CODE REVIEW

File: src/core/src/sys/compute.rs [hunk 1]
```diff
@@ -277,8 +286,11 @@ impl Compute for Stress {
             kinetic += particle.mass * velocity.tensorial(velocity);
         }
 
-        let virial = Virial.compute(system);
-        let volume = Volume.compute(system);
+        let volume = match system.cell().shape() {
```
Comment (antoinewdg) [inline src/core/src/sys/compute.rs]: This piece of code appears three times, maybe it would be useful to put it in a method ?

**Comment by Luthaf** [comment]
> When computing pressure/stress/virial, I set the volume to 1 and carry on with the computation.

What do you think about this? Computing pressure/stress in infinite cell is likely to be wrong, but might still be interesting. If we settle on this behaviour, we should document it.

File: src/core/src/sys/cells.rs [hunk 2]
```diff
@@ -227,6 +227,18 @@ impl UnitCell {
         return volume;
     }
 
+    /// Get the volume of the unit cell if it has periodic boundary conditions, or the `default`
+    /// value.
+    ///
+    /// This function is intended for use where one need to divide unconditionally by the cell
```
Comment (g-bauer) [inline src/core/src/sys/cells.rs]: s/need/needs

**Comment by g-bauer** [comment]
Yes, there needs to be documentation for this behavior - maybe we should also display a warning (`warn_once`). 

Alternatively, we could deny those outputs that "don't make sense" for infinite cells - as you said, they are likely to be wrong or simply not defined.

**Comment by Luthaf** [comment]
> Alternatively, we could deny those outputs that "don't make sense" for infinite cells - as you said, they are likely to be wrong or simply not defined.

I picked this behaviour, as it is less surprising. So now the code will panic if the user try to compute pressure/stress/virial for an infinite cell.

File: src/input/src/simulations/system.rs [hunk 3]
```diff
@@ -50,7 +50,7 @@ impl Input {
         try!(self.read_potentials(&mut system));
         try!(self.init_velocities(&mut system));
 
-        if !with_cell && system.cell().shape() == CellShape::Infinite {
+        if !with_cell && system.cell().is_infinite() {
             warn!("No unit cell in the system, using an infinite unit cell.\n\
             You can silent this warning by using `cell = []` in the input file \
```
Comment (g-bauer) [inline src/input/src/simulations/system.rs]: silent -> mute?

**Comment by Luthaf** [comment]
@g-bauer or @antoinewdg, this is OK for my side !

**Comment by antoinewdg** [comment]
OK for me.
