### PR TITLE
Fix Resize move and add a simple NPT test

### LINKED ISSUE #203: Possibly bug in `resize` MC move
There is possibly a bug in the `resize` MC move (in [`prepare`](https://github.com/lumol-org/lumol/blob/master/src/core/src/sim/mc/moves/resize.rs#L83-L95)). I think we introduced it when we separated `configuration` and `system`.

This is mainly a remainder for me to have another look at it and to figure out a good integration test for NPT.

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #203 

I only added test for an Argon system, molecular system will need #79 to be resolved first.

### CODE REVIEW

**Comment by Luthaf** [comment]
And thank you very much for finding the issue here @g-bauer, this one was really bothering me, but I could not find the origin of the problem.

File: src/core/src/sim/mc/moves/resize.rs [hunk 1]
```diff
@@ -81,13 +81,13 @@ impl MCMove for Resize {
...
-            // so we compute the translation vector of the center-of-mass
-            // (com) of a molecule and apply it to all its particles.
-            // Note that to do this, the com of a molecule *always* has
-            // to reside inside the simulation cell.
+            // We don't want to change the intramolecular distances so we
+            // compute the translation vector of the center-of-mass (com) of a
+            // molecule and apply it to all its particles. Note that to do
+            // this, the com of a molecule *always* has to reside inside the
+            // simulation cell.
             let old_com = system.molecule_com(mi);
```
Comment (g-bauer) [inline src/core/src/sim/mc/moves/resize.rs]: It doesn't make a difference, but I think it would be more clear to use
```rust
let old_com = self.previous.molecule_com(mi);
```
here. Just a nitpick, we can also leave it as is.

**Comment by g-bauer** [comment]
Thanks for the fast fix. Maybe you can comment on my suggestion and I'll merge.

File: src/core/src/sim/mc/moves/resize.rs (hunk 1 above)
Comment (Luthaf) [reply src/core/src/sim/mc/moves/resize.rs]: Yes, this seems more clear =)

**Comment by g-bauer** [comment]
Another "unknown error". Do you want to rerun the test? Else I'd merge.

**Comment by Luthaf** [comment]
I restarted the build.

Just wondering, do you have the rights to restart jobs too?

**Comment by g-bauer** [comment]
Yes, I just wasn't logged in. Next time I can restart the build myself.
